/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

//import com.mysql.jdbc.Connection;
//import com.oracle.jrockit.jfr.ContentType;
import java.awt.Dimension;
import java.awt.Toolkit;
//import java.sql.DriverManager;
//import java.sql.ResultSet;
//import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nitin
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\163-1920.jpg"));
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //MainPage.getFrames()[0].setSize(d);
       // lblImg.setSize(d);
        int wid = (int) d.getWidth();
        int h=(int) d.getHeight();
        int heigh=PanelTop.getHeight();
        MainPage.getFrames()[0].setSize((int)(wid*0.70),(int) (h*0.70));
     //   jPanel1.setVisible(true);
        lblImg.setSize((int) (wid*(0.45)),(int)(h*0.70));
        PanelTop.setSize(wid,heigh);
        PanelSide.setSize((int)(wid*0.25),(int) (h*0.70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        PanelSide = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        PanelTop = new javax.swing.JPanel();
        lblhead = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Steganography in Image Files");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photodune-1258611-secret-m.jpg"))); // NOI18N
        getContentPane().add(lblImg);
        lblImg.setBounds(0, 60, 610, 420);

        PanelSide.setBackground(new java.awt.Color(255, 255, 255));
        PanelSide.setLayout(null);

        lblUser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        lblUser.setText("Username");
        lblUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelSide.add(lblUser);
        lblUser.setBounds(0, 40, 110, 30);

        lblPass.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        lblPass.setText("Password");
        PanelSide.add(lblPass);
        lblPass.setBounds(0, 90, 110, 30);

        txtUser.setText("Nitin");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        PanelSide.add(txtUser);
        txtUser.setBounds(110, 40, 190, 27);

        txtPass.setText("password");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        PanelSide.add(txtPass);
        txtPass.setBounds(110, 90, 190, 27);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        PanelSide.add(jButton1);
        jButton1.setBounds(110, 140, 84, 30);

        getContentPane().add(PanelSide);
        PanelSide.setBounds(610, 60, 310, 420);

        PanelTop.setBackground(new java.awt.Color(255, 255, 255));
        PanelTop.setLayout(null);

        lblhead.setBackground(new java.awt.Color(255, 255, 255));
        lblhead.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("Steganography in Image Files");
        PanelTop.add(lblhead);
        lblhead.setBounds(0, 0, 610, 60);

        getContentPane().add(PanelTop);
        PanelTop.setBounds(0, 0, 930, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try{
               boolean flag=false;
               String usrname=txtUser.getText();
               String pswrd=txtPass.getText();
               txtPass.setText("");
//               Class.forName("com.mysql.jdbc.Driver");
//               java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/steg_login","root","Singla");
//               Statement st=conn.createStatement();
//               ResultSet rs=st.executeQuery("select * from login");
//               if(rs.next())
//               {
//                   if(rs.getString(1).equals(usrname) && rs.getString(2).equals(pswrd))
//                    System.out.println("Nitin is"+usrname);
//                    System.out.println("Password is"+pswrd);
                    if("Nitin".equals(usrname) && "password".equals(pswrd))
                   {
                        flag=true;
                        new MainScreen().setVisible(true);  
                        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                        int wid = (int) d.getWidth();
                        int h=(int) d.getHeight();
                        int heigh=PanelTop.getHeight();
                        MainScreen.getFrames()[1].setSize((int)(wid*0.70),(int) (h*0.70));
                        this.setVisible(false);
                        PanelSide.setVisible(false);
                        PanelTop.setVisible(false);
                        lblImg.setVisible(false);
                   }
//               }
               if(!flag)
               {
                   JOptionPane.showMessageDialog(null, "Enter Correct Username or Password!!", "Error.!!", JOptionPane.ERROR_MESSAGE);
               }
           }
           catch(Exception e){}     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSide;
    private javax.swing.JPanel PanelTop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblhead;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
